import type { GameDefinition } from './types.js';

/** Additional placeholder games — visible in lobby; not playable until implemented */
export const EXTRA_PLACEHOLDER_GAMES: GameDefinition[] = [
  {
    id: 'trivia-blitz',
    name: 'Trivia Blitz',
    description: 'Answer fast-paced trivia before time runs out.',
    supportedModes: ['pc-host', 'mobile-only'],
    minPlayers: 1,
    maxPlayers: 8,
    maxBots: 7,
    status: 'placeholder',
  },
  {
    id: 'word-scramble',
    name: 'Word Scramble',
    description: 'Unscramble words faster than the other players.',
    supportedModes: ['pc-host', 'mobile-only'],
    minPlayers: 1,
    maxPlayers: 8,
    maxBots: 7,
    status: 'placeholder',
  },
  {
    id: 'reaction-dash',
    name: 'Reaction Dash',
    description: 'Tap the moment the signal appears — quickest reflex wins.',
    supportedModes: ['pc-host', 'mobile-only'],
    minPlayers: 2,
    maxPlayers: 8,
    maxBots: 7,
    status: 'placeholder',
  },
  {
    id: 'drawing-guess',
    name: 'Drawing Guess',
    description: 'Sketch the prompt while others guess what you drew.',
    supportedModes: ['pc-host', 'mobile-only'],
    minPlayers: 3,
    maxPlayers: 8,
    maxBots: 5,
    status: 'placeholder',
  },
  {
    id: 'buzzer-beat',
    name: 'Buzzer Beat',
    description: 'First player to buzz in gets to answer the round.',
    supportedModes: ['pc-host', 'mobile-only'],
    minPlayers: 2,
    maxPlayers: 8,
    maxBots: 7,
    status: 'placeholder',
  },
  {
    id: 'color-chaos',
    name: 'Color Chaos',
    description: 'Match the color label to the right button before anyone else.',
    supportedModes: ['pc-host', 'mobile-only'],
    minPlayers: 1,
    maxPlayers: 8,
    maxBots: 7,
    status: 'placeholder',
  },
  {
    id: 'stack-attack',
    name: 'Stack Attack',
    description: 'Stack blocks higher than your opponents without toppling over.',
    supportedModes: ['pc-host', 'mobile-only'],
    minPlayers: 1,
    maxPlayers: 8,
    maxBots: 7,
    status: 'placeholder',
  },
  {
    id: 'vote-off',
    name: 'Vote Off',
    description: 'Debate prompts and vote players off each round.',
    supportedModes: ['pc-host', 'mobile-only', 'personal-computers'],
    minPlayers: 3,
    maxPlayers: 8,
    maxBots: 5,
    status: 'placeholder',
  },
];
